; Song Untitled in Lightweight format (V1).
; Generated by Arkos Tracker 2.

endgame_Start
endgame_StartDisarkGenerateExternalLabel

endgame_DisarkByteRegionStart0
	db "ATLW"	; Format marker (LightWeight).
	db 1	; Format version.
endgame_DisarkByteRegionEnd0
endgame_DisarkPointerRegionStart1
	dw endgame_FmInstrumentTable
	dw endgame_ArpeggioTable
	dw endgame_PitchTable
; Table of the Subsongs.
	dw endgame_Subsong0
endgame_DisarkPointerRegionEnd1

; The Arpeggio table.
endgame_ArpeggioTable
endgame_DisarkWordRegionStart2
	dw 0
endgame_DisarkWordRegionEnd2
endgame_DisarkPointerRegionStart3
endgame_DisarkPointerRegionEnd3

; The Pitch table.
endgame_PitchTable
endgame_DisarkWordRegionStart4
	dw 0
endgame_DisarkWordRegionEnd4
endgame_DisarkPointerRegionStart5
endgame_DisarkPointerRegionEnd5

; The FM Instrument table.
endgame_FmInstrumentTable
endgame_DisarkPointerRegionStart6
	dw endgame_FmInstrument0
	dw endgame_FmInstrument1
	dw endgame_FmInstrument2
	dw endgame_FmInstrument3
	dw endgame_FmInstrument4
	dw endgame_FmInstrument5
endgame_DisarkPointerRegionEnd6

endgame_DisarkByteRegionStart7
endgame_FmInstrument0
	db 255	; Speed.

endgame_FmInstrument0Loop	db 0	; Volume 0.

	db 4	; End the instrument.
endgame_DisarkPointerRegionStart8
	dw endgame_FmInstrument0Loop	; Loops.
endgame_DisarkPointerRegionEnd8

endgame_FmInstrument1
	db 0	; Speed.

	db 189	; Volume 15.
	db 25	; Arpeggio 12.
	db 6	; Noise 6.

	db 189	; Volume 15.
	db 20	; Arpeggio 10.

	db 181	; Volume 13.
	db 18	; Arpeggio 9.

	db 181	; Volume 13.
	db 16	; Arpeggio 8.

	db 173	; Volume 11.
	db 10	; Arpeggio 5.

	db 173	; Volume 11.
	db 8	; Arpeggio 4.

	db 165	; Volume 9.
	db 6	; Arpeggio 3.

	db 157	; Volume 7.
	db 4	; Arpeggio 2.

	db 157	; Volume 7.
	db 2	; Arpeggio 1.

	db 153	; Volume 6.
	db 2	; Arpeggio 1.

	db 25	; Volume 6.

	db 4	; End the instrument.
endgame_DisarkPointerRegionStart9
	dw endgame_FmInstrument0Loop	; Loop to silence.
endgame_DisarkPointerRegionEnd9

endgame_FmInstrument2
	db 0	; Speed.

	db 189	; Volume 15.
	db 27	; Arpeggio 13.
	db 9	; Noise 9.

	db 189	; Volume 15.
	db 18	; Arpeggio 9.

	db 189	; Volume 15.
	db 12	; Arpeggio 6.

	db 181	; Volume 13.
	db 9	; Arpeggio 4.
	db 5	; Noise 5.

	db 173	; Volume 11.
	db 5	; Arpeggio 2.
	db 5	; Noise 5.

	db 4	; End the instrument.
endgame_DisarkPointerRegionStart10
	dw endgame_FmInstrument0Loop	; Loop to silence.
endgame_DisarkPointerRegionEnd10

endgame_FmInstrument3
	db 0	; Speed.

	db 189	; Volume 15.
	db 25	; Arpeggio 12.
	db 11	; Noise 11.

	db 185	; Volume 14.
	db 27	; Arpeggio 13.
	db 10	; Noise 10.

	db 181	; Volume 13.
	db 33	; Arpeggio 16.
	db 9	; Noise 9.

	db 177	; Volume 12.
	db 19	; Arpeggio 9.
	db 8	; Noise 8.

	db 173	; Volume 11.
	db 1	; Arpeggio 0.
	db 7	; Noise 7.

	db 165	; Volume 9.
	db 19	; Arpeggio 9.
	db 6	; Noise 6.

	db 157	; Volume 7.
	db 29	; Arpeggio 14.
	db 5	; Noise 5.

	db 149	; Volume 5.
	db 1	; Arpeggio 0.
	db 4	; Noise 4.

	db 141	; Volume 3.
	db 1	; Arpeggio 0.
	db 3	; Noise 3.

	db 133	; Volume 1.
	db 1	; Arpeggio 0.
	db 2	; Noise 2.

	db 4	; End the instrument.
endgame_DisarkPointerRegionStart11
	dw endgame_FmInstrument0Loop	; Loop to silence.
endgame_DisarkPointerRegionEnd11

endgame_FmInstrument4
	db 0	; Speed.

	db 189	; Volume 15.
	db 8	; Arpeggio 4.

	db 189	; Volume 15.
	db 14	; Arpeggio 7.

	db 185	; Volume 14.
	db 24	; Arpeggio 12.

	db 185	; Volume 14.
	db 8	; Arpeggio 4.

	db 181	; Volume 13.
	db 14	; Arpeggio 7.

	db 181	; Volume 13.
	db 24	; Arpeggio 12.

	db 177	; Volume 12.
	db 8	; Arpeggio 4.

	db 177	; Volume 12.
	db 14	; Arpeggio 7.

	db 173	; Volume 11.
	db 24	; Arpeggio 12.

	db 173	; Volume 11.
	db 8	; Arpeggio 4.

	db 169	; Volume 10.
	db 14	; Arpeggio 7.

	db 169	; Volume 10.
	db 24	; Arpeggio 12.

	db 165	; Volume 9.
	db 8	; Arpeggio 4.

	db 165	; Volume 9.
	db 14	; Arpeggio 7.

	db 161	; Volume 8.
	db 24	; Arpeggio 12.

	db 161	; Volume 8.
	db 8	; Arpeggio 4.

	db 157	; Volume 7.
	db 14	; Arpeggio 7.

	db 157	; Volume 7.
	db 24	; Arpeggio 12.

	db 153	; Volume 6.
	db 8	; Arpeggio 4.

	db 153	; Volume 6.
	db 14	; Arpeggio 7.

	db 149	; Volume 5.
	db 24	; Arpeggio 12.

	db 149	; Volume 5.
	db 8	; Arpeggio 4.

	db 145	; Volume 4.
	db 14	; Arpeggio 7.

	db 145	; Volume 4.
	db 24	; Arpeggio 12.

	db 141	; Volume 3.
	db 8	; Arpeggio 4.

	db 141	; Volume 3.
	db 14	; Arpeggio 7.

	db 137	; Volume 2.
	db 24	; Arpeggio 12.

	db 137	; Volume 2.
	db 8	; Arpeggio 4.

	db 133	; Volume 1.
	db 14	; Arpeggio 7.

	db 4	; End the instrument.
endgame_DisarkPointerRegionStart12
	dw endgame_FmInstrument0Loop	; Loop to silence.
endgame_DisarkPointerRegionEnd12

endgame_FmInstrument5
	db 0	; Speed.

	db 189	; Volume 15.
	db 24	; Arpeggio 12.

	db 53	; Volume 13.

	db 49	; Volume 12.

	db 45	; Volume 11.

	db 41	; Volume 10.

	db 37	; Volume 9.

	db 33	; Volume 8.

	db 29	; Volume 7.

	db 25	; Volume 6.

	db 21	; Volume 5.

	db 17	; Volume 4.

	db 13	; Volume 3.

	db 9	; Volume 2.

	db 5	; Volume 1.

	db 4	; End the instrument.
endgame_DisarkPointerRegionStart13
	dw endgame_FmInstrument0Loop	; Loop to silence.
endgame_DisarkPointerRegionEnd13

endgame_DisarkByteRegionEnd7
endgame_Subsong0DisarkByteRegionStart0
; Song Untitled, Subsong 0 - endgame - in Lightweight format (V1).
; Generated by Arkos Tracker 2.

endgame_Subsong0
	db 6	; Initial speed.

; The Linker.
; Pattern 0
endgame_Subsong0loop
	db 5	; State byte.
	db 63	; New height.
endgame_Subsong0DisarkPointerRegionStart1
	dw endgame_Subsong0_Track2, endgame_Subsong0_Track1, endgame_Subsong0_Track0
endgame_Subsong0DisarkPointerRegionEnd1
; The tracks.

	db 0	; End of the subsong.
endgame_Subsong0DisarkPointerRegionStart2
	dw endgame_Subsong0loop
endgame_Subsong0DisarkPointerRegionEnd2

; The Tracks.
endgame_Subsong0_Track0
	db 61, 63	; Long wait 64.


endgame_Subsong0_Track1
	db 168	; Note 64.
	db 8	; New instrument 4.
	db 126	; Short wait 2.

	db 40	; Note 64.
	db 126	; Short wait 2.

	db 38	; Note 62.
	db 62	; Short wait 1.

	db 40	; Note 64.
	db 61, 54	; Long wait 55.


endgame_Subsong0_Track2
	db 192	; Note 24.
	db 2	; New instrument 1.
	db 128	; Volume + possible Pitch up/down.
	db 191, 14	; Escaped note 14.
	db 10	; New instrument 5.
	db 2	; Note 26.
	db 192	; Note 24.
	db 2	; New instrument 1.
	db 129	; Volume + possible Pitch up/down.
	db 204	; Note 36.
	db 4	; New instrument 2.
	db 128	; Volume + possible Pitch up/down.
	db 142	; Note 38.
	db 10	; New instrument 5.
	db 26	; Note 50.
	db 204	; Note 36.
	db 4	; New instrument 2.
	db 129	; Volume + possible Pitch up/down.
	db 192	; Note 24.
	db 2	; New instrument 1.
	db 128	; Volume + possible Pitch up/down.
	db 130	; Note 26.
	db 10	; New instrument 5.
	db 192	; Note 24.
	db 2	; New instrument 1.
	db 129	; Volume + possible Pitch up/down.
	db 255, 14	; Escaped note 14.
	db 10	; New instrument 5.
	db 128	; Volume + possible Pitch up/down.
	db 204	; Note 36.
	db 4	; New instrument 2.
	db 129	; Volume + possible Pitch up/down.
	db 142	; Note 38.
	db 10	; New instrument 5.
	db 128	; Note 24.
	db 2	; New instrument 1.
	db 204	; Note 36.
	db 4	; New instrument 2.
	db 130	; Volume + possible Pitch up/down.
	db 128	; Note 24.
	db 2	; New instrument 1.
	db 191, 14	; Escaped note 14.
	db 10	; New instrument 5.
	db 66	; Note 26.
	db 131	; Volume + possible Pitch up/down.
	db 128	; Note 24.
	db 2	; New instrument 1.
	db 140	; Note 36.
	db 4	; New instrument 2.
	db 142	; Note 38.
	db 10	; New instrument 5.
	db 26	; Note 50.
	db 204	; Note 36.
	db 4	; New instrument 2.
	db 132	; Volume + possible Pitch up/down.
	db 128	; Note 24.
	db 2	; New instrument 1.
	db 130	; Note 26.
	db 10	; New instrument 5.
	db 128	; Note 24.
	db 2	; New instrument 1.
	db 191, 14	; Escaped note 14.
	db 10	; New instrument 5.
	db 204	; Note 36.
	db 4	; New instrument 2.
	db 133	; Volume + possible Pitch up/down.
	db 142	; Note 38.
	db 10	; New instrument 5.
	db 128	; Note 24.
	db 2	; New instrument 1.
	db 140	; Note 36.
	db 4	; New instrument 2.
	db 128	; Note 24.
	db 2	; New instrument 1.
	db 191, 19	; Escaped note 19.
	db 10	; New instrument 5.
	db 7	; Note 31.
	db 192	; Note 24.
	db 2	; New instrument 1.
	db 134	; Volume + possible Pitch up/down.
	db 140	; Note 36.
	db 4	; New instrument 2.
	db 147	; Note 43.
	db 10	; New instrument 5.
	db 31	; Note 55.
	db 140	; Note 36.
	db 4	; New instrument 2.
	db 128	; Note 24.
	db 2	; New instrument 1.
	db 199	; Note 31.
	db 10	; New instrument 5.
	db 135	; Volume + possible Pitch up/down.
	db 128	; Note 24.
	db 2	; New instrument 1.
	db 191, 19	; Escaped note 19.
	db 10	; New instrument 5.
	db 140	; Note 36.
	db 4	; New instrument 2.
	db 142	; Note 38.
	db 10	; New instrument 5.
	db 192	; Note 24.
	db 2	; New instrument 1.
	db 136	; Volume + possible Pitch up/down.
	db 140	; Note 36.
	db 4	; New instrument 2.
	db 128	; Note 24.
	db 2	; New instrument 1.
	db 191, 9	; Escaped note 9.
	db 10	; New instrument 5.
	db 127, 21	; Escaped note 21.
	db 137	; Volume + possible Pitch up/down.
	db 128	; Note 24.
	db 2	; New instrument 1.
	db 140	; Note 36.
	db 4	; New instrument 2.
	db 137	; Note 33.
	db 10	; New instrument 5.
	db 85	; Note 45.
	db 138	; Volume + possible Pitch up/down.
	db 140	; Note 36.
	db 4	; New instrument 2.
	db 140	; Note 36.
	db 2	; New instrument 1.
	db 191, 21	; Escaped note 21.
	db 10	; New instrument 5.
	db 204	; Note 36.
	db 4	; New instrument 2.
	db 139	; Volume + possible Pitch up/down.
	db 191, 9	; Escaped note 9.
	db 10	; New instrument 5.
	db 145	; Note 41.
	db 6	; New instrument 3.
	db 206	; Note 38.
	db 10	; New instrument 5.
	db 140	; Volume + possible Pitch up/down.
	db 145	; Note 41.
	db 6	; New instrument 3.
	db 81	; Note 41.
	db 141	; Volume + possible Pitch up/down.

endgame_Subsong0DisarkByteRegionEnd0
