; Sound Effects for song New song, version 2.0, generated by Arkos Tracker 2.

Newsong_SoundEffects

; The sound effects, starting at 1.
Newsong_SoundEffectsDisarkPointerRegionStart0
	dw Newsong_SoundEffects_Sound1	; Sound effect 1.
	dw Newsong_SoundEffects_Sound2	; Sound effect 2.
	dw Newsong_SoundEffects_Sound3	; Sound effect 3.
Newsong_SoundEffectsDisarkPointerRegionEnd0

Newsong_SoundEffectsDisarkByteRegionStart1
; Sound effect 1.
Newsong_SoundEffects_Sound1
	db 0	; Speed

Newsong_SoundEffects_Sound1_Loop	db 189	; Soft only. Volume 15.
	db 15	; Noise 15.
	dw 1612	; Software period.

	db 189	; Soft only. Volume 15.
	db 15	; Noise 15.
	dw 638	; Software period.

	db 189	; Soft only. Volume 15.
	db 15	; Noise 15.
	dw 402	; Software period.

	db 189	; Soft only. Volume 15.
	db 15	; Noise 15.
	dw 1522	; Software period.

	db 185	; Soft only. Volume 14.
	db 15	; Noise 15.
	dw 603	; Software period.

	db 185	; Soft only. Volume 14.
	db 15	; Noise 15.
	dw 380	; Software period.

	db 185	; Soft only. Volume 14.
	db 15	; Noise 15.
	dw 1437	; Software period.

	db 181	; Soft only. Volume 13.
	db 15	; Noise 15.
	dw 570	; Software period.

	db 181	; Soft only. Volume 13.
	db 15	; Noise 15.
	dw 358	; Software period.

	db 181	; Soft only. Volume 13.
	db 15	; Noise 15.
	dw 1355	; Software period.

	db 177	; Soft only. Volume 12.
	db 15	; Noise 15.
	dw 537	; Software period.

	db 177	; Soft only. Volume 12.
	db 15	; Noise 15.
	dw 338	; Software period.

	db 177	; Soft only. Volume 12.
	db 15	; Noise 15.
	dw 1278	; Software period.

	db 173	; Soft only. Volume 11.
	db 15	; Noise 15.
	dw 507	; Software period.

	db 173	; Soft only. Volume 11.
	db 15	; Noise 15.
	dw 318	; Software period.

	db 173	; Soft only. Volume 11.
	db 15	; Noise 15.
	dw 1208	; Software period.

	db 169	; Soft only. Volume 10.
	db 15	; Noise 15.
	dw 478	; Software period.

	db 169	; Soft only. Volume 10.
	db 15	; Noise 15.
	dw 301	; Software period.

	db 169	; Soft only. Volume 10.
	db 15	; Noise 15.
	dw 1140	; Software period.

	db 169	; Soft only. Volume 10.
	db 15	; Noise 15.
	dw 452	; Software period.

	db 165	; Soft only. Volume 9.
	db 15	; Noise 15.
	dw 285	; Software period.

	db 165	; Soft only. Volume 9.
	db 15	; Noise 15.
	dw 1076	; Software period.

	db 165	; Soft only. Volume 9.
	db 15	; Noise 15.
	dw 426	; Software period.

	db 161	; Soft only. Volume 8.
	db 15	; Noise 15.
	dw 268	; Software period.

	db 161	; Soft only. Volume 8.
	db 15	; Noise 15.
	dw 1016	; Software period.

	db 161	; Soft only. Volume 8.
	db 15	; Noise 15.
	dw 402	; Software period.

	db 161	; Soft only. Volume 8.
	db 15	; Noise 15.
	dw 253	; Software period.

	db 4	; End of the sound effect.

; Sound effect 2.
Newsong_SoundEffects_Sound2
	db 0	; Speed

Newsong_SoundEffects_Sound2_Loop	db 181	; Soft only. Volume 13.
	db 28	; Noise 28.
	dw 587	; Software period.

	db 181	; Soft only. Volume 13.
	db 28	; Noise 28.
	dw 587	; Software period.

	db 189	; Soft only. Volume 15.
	db 29	; Noise 29.
	dw 831	; Software period.

	db 189	; Soft only. Volume 15.
	db 29	; Noise 29.
	dw 831	; Software period.

	db 185	; Soft only. Volume 14.
	db 28	; Noise 28.
	dw 587	; Software period.

	db 185	; Soft only. Volume 14.
	db 28	; Noise 28.
	dw 587	; Software period.

	db 181	; Soft only. Volume 13.
	db 27	; Noise 27.
	dw 343	; Software period.

	db 181	; Soft only. Volume 13.
	db 27	; Noise 27.
	dw 343	; Software period.

	db 181	; Soft only. Volume 13.
	db 26	; Noise 26.
	dw 587	; Software period.

	db 181	; Soft only. Volume 13.
	db 26	; Noise 26.
	dw 587	; Software period.

	db 177	; Soft only. Volume 12.
	db 27	; Noise 27.
	dw 831	; Software period.

	db 177	; Soft only. Volume 12.
	db 27	; Noise 27.
	dw 831	; Software period.

	db 177	; Soft only. Volume 12.
	db 28	; Noise 28.
	dw 587	; Software period.

	db 177	; Soft only. Volume 12.
	db 28	; Noise 28.
	dw 587	; Software period.

	db 173	; Soft only. Volume 11.
	db 27	; Noise 27.
	dw 343	; Software period.

	db 173	; Soft only. Volume 11.
	db 27	; Noise 27.
	dw 343	; Software period.

	db 173	; Soft only. Volume 11.
	db 26	; Noise 26.
	dw 587	; Software period.

	db 173	; Soft only. Volume 11.
	db 26	; Noise 26.
	dw 587	; Software period.

	db 173	; Soft only. Volume 11.
	db 25	; Noise 25.
	dw 831	; Software period.

	db 173	; Soft only. Volume 11.
	db 25	; Noise 25.
	dw 831	; Software period.

	db 169	; Soft only. Volume 10.
	db 26	; Noise 26.
	dw 587	; Software period.

	db 169	; Soft only. Volume 10.
	db 26	; Noise 26.
	dw 587	; Software period.

	db 169	; Soft only. Volume 10.
	db 27	; Noise 27.
	dw 343	; Software period.

	db 169	; Soft only. Volume 10.
	db 27	; Noise 27.
	dw 343	; Software period.

	db 169	; Soft only. Volume 10.
	db 26	; Noise 26.
	dw 587	; Software period.

	db 169	; Soft only. Volume 10.
	db 26	; Noise 26.
	dw 587	; Software period.

	db 165	; Soft only. Volume 9.
	db 25	; Noise 25.
	dw 831	; Software period.

	db 165	; Soft only. Volume 9.
	db 25	; Noise 25.
	dw 831	; Software period.

	db 165	; Soft only. Volume 9.
	db 24	; Noise 24.
	dw 587	; Software period.

	db 165	; Soft only. Volume 9.
	db 24	; Noise 24.
	dw 587	; Software period.

	db 165	; Soft only. Volume 9.
	db 25	; Noise 25.
	dw 343	; Software period.

	db 165	; Soft only. Volume 9.
	db 25	; Noise 25.
	dw 343	; Software period.

	db 161	; Soft only. Volume 8.
	db 26	; Noise 26.
	dw 587	; Software period.

	db 161	; Soft only. Volume 8.
	db 26	; Noise 26.
	dw 587	; Software period.

	db 161	; Soft only. Volume 8.
	db 25	; Noise 25.
	dw 831	; Software period.

	db 161	; Soft only. Volume 8.
	db 25	; Noise 25.
	dw 831	; Software period.

	db 161	; Soft only. Volume 8.
	db 24	; Noise 24.
	dw 587	; Software period.

	db 161	; Soft only. Volume 8.
	db 24	; Noise 24.
	dw 587	; Software period.

	db 157	; Soft only. Volume 7.
	db 23	; Noise 23.
	dw 343	; Software period.

	db 157	; Soft only. Volume 7.
	db 23	; Noise 23.
	dw 343	; Software period.

	db 157	; Soft only. Volume 7.
	db 24	; Noise 24.
	dw 587	; Software period.

	db 157	; Soft only. Volume 7.
	db 24	; Noise 24.
	dw 587	; Software period.

	db 157	; Soft only. Volume 7.
	db 25	; Noise 25.
	dw 831	; Software period.

	db 157	; Soft only. Volume 7.
	db 25	; Noise 25.
	dw 831	; Software period.

	db 153	; Soft only. Volume 6.
	db 24	; Noise 24.
	dw 587	; Software period.

	db 153	; Soft only. Volume 6.
	db 24	; Noise 24.
	dw 587	; Software period.

	db 153	; Soft only. Volume 6.
	db 23	; Noise 23.
	dw 343	; Software period.

	db 153	; Soft only. Volume 6.
	db 23	; Noise 23.
	dw 343	; Software period.

	db 153	; Soft only. Volume 6.
	db 22	; Noise 22.
	dw 587	; Software period.

	db 153	; Soft only. Volume 6.
	db 22	; Noise 22.
	dw 587	; Software period.

	db 149	; Soft only. Volume 5.
	db 23	; Noise 23.
	dw 831	; Software period.

	db 149	; Soft only. Volume 5.
	db 23	; Noise 23.
	dw 831	; Software period.

	db 149	; Soft only. Volume 5.
	db 24	; Noise 24.
	dw 587	; Software period.

	db 149	; Soft only. Volume 5.
	db 24	; Noise 24.
	dw 587	; Software period.

	db 149	; Soft only. Volume 5.
	db 23	; Noise 23.
	dw 343	; Software period.

	db 149	; Soft only. Volume 5.
	db 23	; Noise 23.
	dw 343	; Software period.

	db 145	; Soft only. Volume 4.
	db 22	; Noise 22.
	dw 587	; Software period.

	db 145	; Soft only. Volume 4.
	db 22	; Noise 22.
	dw 587	; Software period.

	db 145	; Soft only. Volume 4.
	db 21	; Noise 21.
	dw 831	; Software period.

	db 145	; Soft only. Volume 4.
	db 21	; Noise 21.
	dw 831	; Software period.

	db 145	; Soft only. Volume 4.
	db 22	; Noise 22.
	dw 587	; Software period.

	db 145	; Soft only. Volume 4.
	db 22	; Noise 22.
	dw 587	; Software period.

	db 145	; Soft only. Volume 4.
	db 23	; Noise 23.
	dw 343	; Software period.

	db 145	; Soft only. Volume 4.
	db 23	; Noise 23.
	dw 343	; Software period.

	db 145	; Soft only. Volume 4.
	db 22	; Noise 22.
	dw 587	; Software period.

	db 145	; Soft only. Volume 4.
	db 22	; Noise 22.
	dw 587	; Software period.

	db 145	; Soft only. Volume 4.
	db 21	; Noise 21.
	dw 831	; Software period.

	db 145	; Soft only. Volume 4.
	db 21	; Noise 21.
	dw 831	; Software period.

	db 145	; Soft only. Volume 4.
	db 20	; Noise 20.
	dw 587	; Software period.

	db 145	; Soft only. Volume 4.
	db 20	; Noise 20.
	dw 587	; Software period.

	db 145	; Soft only. Volume 4.
	db 21	; Noise 21.
	dw 343	; Software period.

	db 145	; Soft only. Volume 4.
	db 21	; Noise 21.
	dw 343	; Software period.

	db 145	; Soft only. Volume 4.
	db 22	; Noise 22.
	dw 587	; Software period.

	db 145	; Soft only. Volume 4.
	db 22	; Noise 22.
	dw 587	; Software period.

	db 4	; End of the sound effect.

; Sound effect 3.
Newsong_SoundEffects_Sound3
	db 0	; Speed

Newsong_SoundEffects_Sound3_Loop	db 189	; Soft only. Volume 15.
	db 6	; Noise 6.
	dw 50	; Software period.

	db 61	; Soft only. Volume 15.
	dw 566	; Software period.

	db 161	; Soft only. Volume 8.
	db 2	; Noise 2.
	dw 566	; Software period.

	db 161	; Soft only. Volume 8.
	db 2	; Noise 2.
	dw 566	; Software period.

	db 4	; End of the sound effect.

Newsong_SoundEffectsDisarkByteRegionEnd1

