; Song Untitled in Lightweight format (V1).
; Generated by Arkos Tracker 2.

Untitled_SongStart
Untitled_DisarkByteRegionStart0
	db "ATLW"	; Format marker (LightWeight).
	db 1	; Format version.
Untitled_DisarkByteRegionEnd0
Untitled_DisarkPointerRegionStart1
	dw Untitled_FmInstrumentTable
	dw Untitled_ArpeggioTable
	dw Untitled_PitchTable
; Table of the Subsongs.
	dw Untitled_Subsong0
Untitled_DisarkPointerRegionEnd1

; The Arpeggio table.
Untitled_ArpeggioTable
Untitled_DisarkWordRegionStart2
	dw 0
Untitled_DisarkWordRegionEnd2
Untitled_DisarkPointerRegionStart3
Untitled_DisarkPointerRegionEnd3

; The Pitch table.
Untitled_PitchTable
Untitled_DisarkWordRegionStart4
	dw 0
Untitled_DisarkWordRegionEnd4
Untitled_DisarkPointerRegionStart5
Untitled_DisarkPointerRegionEnd5

; The FM Instrument table.
Untitled_FmInstrumentTable
Untitled_DisarkPointerRegionStart6
	dw Untitled_FmInstrument0
	dw Untitled_FmInstrument1
	dw Untitled_FmInstrument2
	dw Untitled_FmInstrument3
	dw Untitled_FmInstrument4
Untitled_DisarkPointerRegionEnd6

Untitled_DisarkByteRegionStart7
Untitled_FmInstrument0
	db 255	; Speed.

Untitled_FmInstrument0Loop	db 0	; Volume 0.

	db 4	; End the instrument.
Untitled_DisarkPointerRegionStart8
	dw Untitled_FmInstrument0Loop	; Loops.
Untitled_DisarkPointerRegionEnd8

Untitled_FmInstrument1
	db 0	; Speed.

	db 189	; Volume 15.
	db 25	; Arpeggio 12.
	db 6	; Noise 6.

	db 189	; Volume 15.
	db 20	; Arpeggio 10.

	db 181	; Volume 13.
	db 18	; Arpeggio 9.

	db 181	; Volume 13.
	db 16	; Arpeggio 8.

	db 173	; Volume 11.
	db 10	; Arpeggio 5.

	db 173	; Volume 11.
	db 8	; Arpeggio 4.

	db 165	; Volume 9.
	db 6	; Arpeggio 3.

	db 157	; Volume 7.
	db 4	; Arpeggio 2.

	db 157	; Volume 7.
	db 2	; Arpeggio 1.

	db 153	; Volume 6.
	db 2	; Arpeggio 1.

	db 25	; Volume 6.

	db 4	; End the instrument.
Untitled_DisarkPointerRegionStart9
	dw Untitled_FmInstrument0Loop	; Loop to silence.
Untitled_DisarkPointerRegionEnd9

Untitled_FmInstrument2
	db 0	; Speed.

	db 189	; Volume 15.
	db 27	; Arpeggio 13.
	db 9	; Noise 9.

	db 189	; Volume 15.
	db 18	; Arpeggio 9.

	db 189	; Volume 15.
	db 12	; Arpeggio 6.

	db 181	; Volume 13.
	db 9	; Arpeggio 4.
	db 5	; Noise 5.

	db 173	; Volume 11.
	db 5	; Arpeggio 2.
	db 5	; Noise 5.

	db 4	; End the instrument.
Untitled_DisarkPointerRegionStart10
	dw Untitled_FmInstrument0Loop	; Loop to silence.
Untitled_DisarkPointerRegionEnd10

Untitled_FmInstrument3
	db 0	; Speed.

	db 189	; Volume 15.
	db 25	; Arpeggio 12.
	db 11	; Noise 11.

	db 185	; Volume 14.
	db 27	; Arpeggio 13.
	db 10	; Noise 10.

	db 181	; Volume 13.
	db 33	; Arpeggio 16.
	db 9	; Noise 9.

	db 177	; Volume 12.
	db 19	; Arpeggio 9.
	db 8	; Noise 8.

	db 173	; Volume 11.
	db 1	; Arpeggio 0.
	db 7	; Noise 7.

	db 165	; Volume 9.
	db 19	; Arpeggio 9.
	db 6	; Noise 6.

	db 157	; Volume 7.
	db 29	; Arpeggio 14.
	db 5	; Noise 5.

	db 149	; Volume 5.
	db 1	; Arpeggio 0.
	db 4	; Noise 4.

	db 141	; Volume 3.
	db 1	; Arpeggio 0.
	db 3	; Noise 3.

	db 133	; Volume 1.
	db 1	; Arpeggio 0.
	db 2	; Noise 2.

	db 4	; End the instrument.
Untitled_DisarkPointerRegionStart11
	dw Untitled_FmInstrument0Loop	; Loop to silence.
Untitled_DisarkPointerRegionEnd11

Untitled_FmInstrument4
	db 0	; Speed.

	db 189	; Volume 15.
	db 24	; Arpeggio 12.

	db 53	; Volume 13.

	db 49	; Volume 12.

	db 45	; Volume 11.

	db 41	; Volume 10.

	db 37	; Volume 9.

	db 33	; Volume 8.

	db 29	; Volume 7.

	db 25	; Volume 6.

	db 21	; Volume 5.

	db 17	; Volume 4.

	db 13	; Volume 3.

	db 9	; Volume 2.

	db 5	; Volume 1.

	db 4	; End the instrument.
Untitled_DisarkPointerRegionStart12
	dw Untitled_FmInstrument0Loop	; Loop to silence.
Untitled_DisarkPointerRegionEnd12

Untitled_DisarkByteRegionEnd7
Untitled_Subsong0DisarkByteRegionStart0
; Song Untitled, Subsong 0 - Main - in Lightweight format (V1).
; Generated by Arkos Tracker 2.

Untitled_Subsong0
	db 6	; Initial speed.

; The Linker.
; Pattern 0
	db 5	; State byte.
	db 63	; New height.
Untitled_Subsong0DisarkPointerRegionStart1
	dw Untitled_Subsong0_Track0, Untitled_Subsong0_Track1, Untitled_Subsong0_Track1
Untitled_Subsong0DisarkPointerRegionEnd1
; The tracks.

; Pattern 1
Untitled_Subsong0loop
	db 9	; State byte.
	db 0, 0, 0	; The transpositions.
Untitled_Subsong0DisarkPointerRegionStart2
	dw Untitled_Subsong0_Track2, Untitled_Subsong0_Track1, Untitled_Subsong0_Track1
Untitled_Subsong0DisarkPointerRegionEnd2
; The tracks.

; Pattern 2
	db 1	; State byte.
Untitled_Subsong0DisarkPointerRegionStart3
	dw Untitled_Subsong0_Track0, Untitled_Subsong0_Track1, Untitled_Subsong0_Track1
Untitled_Subsong0DisarkPointerRegionEnd3
; The tracks.

; Pattern 3
	db 1	; State byte.
Untitled_Subsong0DisarkPointerRegionStart4
	dw Untitled_Subsong0_Track2, Untitled_Subsong0_Track1, Untitled_Subsong0_Track1
Untitled_Subsong0DisarkPointerRegionEnd4
; The tracks.

; Pattern 4
	db 9	; State byte.
	db 7, 2, 7	; The transpositions.
Untitled_Subsong0DisarkPointerRegionStart5
	dw Untitled_Subsong0_Track2, Untitled_Subsong0_Track1, Untitled_Subsong0_Track1
Untitled_Subsong0DisarkPointerRegionEnd5
; The tracks.

; Pattern 5
	db 9	; State byte.
	db 5, 5, 5	; The transpositions.
Untitled_Subsong0DisarkPointerRegionStart6
	dw Untitled_Subsong0_Track0, Untitled_Subsong0_Track1, Untitled_Subsong0_Track1
Untitled_Subsong0DisarkPointerRegionEnd6
; The tracks.

; Pattern 6
	db 1	; State byte.
Untitled_Subsong0DisarkPointerRegionStart7
	dw Untitled_Subsong0_Track2, Untitled_Subsong0_Track1, Untitled_Subsong0_Track1
Untitled_Subsong0DisarkPointerRegionEnd7
; The tracks.

; Pattern 7
	db 9	; State byte.
	db 0, -5, 0	; The transpositions.
Untitled_Subsong0DisarkPointerRegionStart8
	dw Untitled_Subsong0_Track0, Untitled_Subsong0_Track1, Untitled_Subsong0_Track1
Untitled_Subsong0DisarkPointerRegionEnd8
; The tracks.

; Pattern 8
	db 9	; State byte.
	db 0, 0, 0	; The transpositions.
Untitled_Subsong0DisarkPointerRegionStart9
	dw Untitled_Subsong0_Track2, Untitled_Subsong0_Track1, Untitled_Subsong0_Track1
Untitled_Subsong0DisarkPointerRegionEnd9
; The tracks.

; Pattern 9
	db 9	; State byte.
	db 7, 2, 7	; The transpositions.
Untitled_Subsong0DisarkPointerRegionStart10
	dw Untitled_Subsong0_Track0, Untitled_Subsong0_Track1, Untitled_Subsong0_Track1
Untitled_Subsong0DisarkPointerRegionEnd10
; The tracks.

; Pattern 10
	db 9	; State byte.
	db 5, 5, 5	; The transpositions.
Untitled_Subsong0DisarkPointerRegionStart11
	dw Untitled_Subsong0_Track0, Untitled_Subsong0_Track1, Untitled_Subsong0_Track1
Untitled_Subsong0DisarkPointerRegionEnd11
; The tracks.

; Pattern 11
	db 1	; State byte.
Untitled_Subsong0DisarkPointerRegionStart12
	dw Untitled_Subsong0_Track2, Untitled_Subsong0_Track1, Untitled_Subsong0_Track1
Untitled_Subsong0DisarkPointerRegionEnd12
; The tracks.

; Pattern 12
	db 9	; State byte.
	db -5, -5, -5	; The transpositions.
Untitled_Subsong0DisarkPointerRegionStart13
	dw Untitled_Subsong0_Track0, Untitled_Subsong0_Track1, Untitled_Subsong0_Track1
Untitled_Subsong0DisarkPointerRegionEnd13
; The tracks.

; Pattern 13
	db 1	; State byte.
Untitled_Subsong0DisarkPointerRegionStart14
	dw Untitled_Subsong0_Track2, Untitled_Subsong0_Track1, Untitled_Subsong0_Track1
Untitled_Subsong0DisarkPointerRegionEnd14
; The tracks.

	db 0	; End of the subsong.
Untitled_Subsong0DisarkPointerRegionStart15
	dw Untitled_Subsong0loop
Untitled_Subsong0DisarkPointerRegionEnd15

; The Tracks.
Untitled_Subsong0_Track0
	db 192	; Note 24.
	db 2	; New instrument 1.
	db 128	; Volume + possible Pitch up/down.
	db 191, 14	; Escaped note 14.
	db 8	; New instrument 4.
	db 2	; Note 26.
	db 192	; Note 24.
	db 2	; New instrument 1.
	db 129	; Volume + possible Pitch up/down.
	db 204	; Note 36.
	db 4	; New instrument 2.
	db 128	; Volume + possible Pitch up/down.
	db 142	; Note 38.
	db 8	; New instrument 4.
	db 26	; Note 50.
	db 204	; Note 36.
	db 4	; New instrument 2.
	db 129	; Volume + possible Pitch up/down.
	db 192	; Note 24.
	db 2	; New instrument 1.
	db 128	; Volume + possible Pitch up/down.
	db 130	; Note 26.
	db 8	; New instrument 4.
	db 192	; Note 24.
	db 2	; New instrument 1.
	db 129	; Volume + possible Pitch up/down.
	db 255, 14	; Escaped note 14.
	db 8	; New instrument 4.
	db 128	; Volume + possible Pitch up/down.
	db 140	; Note 36.
	db 4	; New instrument 2.
	db 142	; Note 38.
	db 8	; New instrument 4.
	db 128	; Note 24.
	db 2	; New instrument 1.
	db 140	; Note 36.
	db 4	; New instrument 2.
	db 128	; Note 24.
	db 2	; New instrument 1.
	db 191, 14	; Escaped note 14.
	db 8	; New instrument 4.
	db 2	; Note 26.
	db 192	; Note 24.
	db 2	; New instrument 1.
	db 129	; Volume + possible Pitch up/down.
	db 204	; Note 36.
	db 4	; New instrument 2.
	db 128	; Volume + possible Pitch up/down.
	db 142	; Note 38.
	db 8	; New instrument 4.
	db 26	; Note 50.
	db 204	; Note 36.
	db 4	; New instrument 2.
	db 129	; Volume + possible Pitch up/down.
	db 192	; Note 24.
	db 2	; New instrument 1.
	db 128	; Volume + possible Pitch up/down.
	db 130	; Note 26.
	db 8	; New instrument 4.
	db 192	; Note 24.
	db 2	; New instrument 1.
	db 129	; Volume + possible Pitch up/down.
	db 255, 14	; Escaped note 14.
	db 8	; New instrument 4.
	db 128	; Volume + possible Pitch up/down.
	db 140	; Note 36.
	db 4	; New instrument 2.
	db 142	; Note 38.
	db 8	; New instrument 4.
	db 128	; Note 24.
	db 2	; New instrument 1.
	db 140	; Note 36.
	db 4	; New instrument 2.
	db 128	; Note 24.
	db 2	; New instrument 1.
	db 191, 19	; Escaped note 19.
	db 8	; New instrument 4.
	db 7	; Note 31.
	db 192	; Note 24.
	db 2	; New instrument 1.
	db 129	; Volume + possible Pitch up/down.
	db 204	; Note 36.
	db 4	; New instrument 2.
	db 128	; Volume + possible Pitch up/down.
	db 147	; Note 43.
	db 8	; New instrument 4.
	db 31	; Note 55.
	db 204	; Note 36.
	db 4	; New instrument 2.
	db 129	; Volume + possible Pitch up/down.
	db 192	; Note 24.
	db 2	; New instrument 1.
	db 128	; Volume + possible Pitch up/down.
	db 135	; Note 31.
	db 8	; New instrument 4.
	db 192	; Note 24.
	db 2	; New instrument 1.
	db 129	; Volume + possible Pitch up/down.
	db 255, 19	; Escaped note 19.
	db 8	; New instrument 4.
	db 128	; Volume + possible Pitch up/down.
	db 140	; Note 36.
	db 4	; New instrument 2.
	db 142	; Note 38.
	db 8	; New instrument 4.
	db 128	; Note 24.
	db 2	; New instrument 1.
	db 140	; Note 36.
	db 4	; New instrument 2.
	db 128	; Note 24.
	db 2	; New instrument 1.
	db 191, 9	; Escaped note 9.
	db 8	; New instrument 4.
	db 63, 21	; Escaped note 21.
	db 192	; Note 24.
	db 2	; New instrument 1.
	db 129	; Volume + possible Pitch up/down.
	db 204	; Note 36.
	db 4	; New instrument 2.
	db 128	; Volume + possible Pitch up/down.
	db 137	; Note 33.
	db 8	; New instrument 4.
	db 21	; Note 45.
	db 204	; Note 36.
	db 4	; New instrument 2.
	db 129	; Volume + possible Pitch up/down.
	db 192	; Note 24.
	db 2	; New instrument 1.
	db 128	; Volume + possible Pitch up/down.
	db 191, 21	; Escaped note 21.
	db 8	; New instrument 4.
	db 192	; Note 24.
	db 2	; New instrument 1.
	db 129	; Volume + possible Pitch up/down.
	db 255, 9	; Escaped note 9.
	db 8	; New instrument 4.
	db 128	; Volume + possible Pitch up/down.
	db 140	; Note 36.
	db 4	; New instrument 2.
	db 142	; Note 38.
	db 8	; New instrument 4.
	db 204	; Note 36.
	db 4	; New instrument 2.
	db 129	; Volume + possible Pitch up/down.
	db 76	; Note 36.
	db 128	; Volume + possible Pitch up/down.

Untitled_Subsong0_Track1
	db 61, 63	; Long wait 64.


Untitled_Subsong0_Track2
	db 192	; Note 24.
	db 2	; New instrument 1.
	db 128	; Volume + possible Pitch up/down.
	db 191, 14	; Escaped note 14.
	db 8	; New instrument 4.
	db 2	; Note 26.
	db 192	; Note 24.
	db 2	; New instrument 1.
	db 129	; Volume + possible Pitch up/down.
	db 204	; Note 36.
	db 4	; New instrument 2.
	db 128	; Volume + possible Pitch up/down.
	db 142	; Note 38.
	db 8	; New instrument 4.
	db 26	; Note 50.
	db 204	; Note 36.
	db 4	; New instrument 2.
	db 129	; Volume + possible Pitch up/down.
	db 192	; Note 24.
	db 2	; New instrument 1.
	db 128	; Volume + possible Pitch up/down.
	db 130	; Note 26.
	db 8	; New instrument 4.
	db 192	; Note 24.
	db 2	; New instrument 1.
	db 129	; Volume + possible Pitch up/down.
	db 255, 14	; Escaped note 14.
	db 8	; New instrument 4.
	db 128	; Volume + possible Pitch up/down.
	db 140	; Note 36.
	db 4	; New instrument 2.
	db 142	; Note 38.
	db 8	; New instrument 4.
	db 128	; Note 24.
	db 2	; New instrument 1.
	db 140	; Note 36.
	db 4	; New instrument 2.
	db 128	; Note 24.
	db 2	; New instrument 1.
	db 191, 14	; Escaped note 14.
	db 8	; New instrument 4.
	db 2	; Note 26.
	db 192	; Note 24.
	db 2	; New instrument 1.
	db 129	; Volume + possible Pitch up/down.
	db 204	; Note 36.
	db 4	; New instrument 2.
	db 128	; Volume + possible Pitch up/down.
	db 142	; Note 38.
	db 8	; New instrument 4.
	db 26	; Note 50.
	db 204	; Note 36.
	db 4	; New instrument 2.
	db 129	; Volume + possible Pitch up/down.
	db 192	; Note 24.
	db 2	; New instrument 1.
	db 128	; Volume + possible Pitch up/down.
	db 130	; Note 26.
	db 8	; New instrument 4.
	db 192	; Note 24.
	db 2	; New instrument 1.
	db 129	; Volume + possible Pitch up/down.
	db 255, 14	; Escaped note 14.
	db 8	; New instrument 4.
	db 128	; Volume + possible Pitch up/down.
	db 140	; Note 36.
	db 4	; New instrument 2.
	db 142	; Note 38.
	db 8	; New instrument 4.
	db 128	; Note 24.
	db 2	; New instrument 1.
	db 140	; Note 36.
	db 4	; New instrument 2.
	db 128	; Note 24.
	db 2	; New instrument 1.
	db 191, 19	; Escaped note 19.
	db 8	; New instrument 4.
	db 7	; Note 31.
	db 192	; Note 24.
	db 2	; New instrument 1.
	db 129	; Volume + possible Pitch up/down.
	db 204	; Note 36.
	db 4	; New instrument 2.
	db 128	; Volume + possible Pitch up/down.
	db 147	; Note 43.
	db 8	; New instrument 4.
	db 31	; Note 55.
	db 204	; Note 36.
	db 4	; New instrument 2.
	db 129	; Volume + possible Pitch up/down.
	db 192	; Note 24.
	db 2	; New instrument 1.
	db 128	; Volume + possible Pitch up/down.
	db 135	; Note 31.
	db 8	; New instrument 4.
	db 192	; Note 24.
	db 2	; New instrument 1.
	db 129	; Volume + possible Pitch up/down.
	db 255, 19	; Escaped note 19.
	db 8	; New instrument 4.
	db 128	; Volume + possible Pitch up/down.
	db 140	; Note 36.
	db 4	; New instrument 2.
	db 142	; Note 38.
	db 8	; New instrument 4.
	db 128	; Note 24.
	db 2	; New instrument 1.
	db 140	; Note 36.
	db 4	; New instrument 2.
	db 128	; Note 24.
	db 2	; New instrument 1.
	db 191, 9	; Escaped note 9.
	db 8	; New instrument 4.
	db 63, 21	; Escaped note 21.
	db 192	; Note 24.
	db 2	; New instrument 1.
	db 129	; Volume + possible Pitch up/down.
	db 204	; Note 36.
	db 4	; New instrument 2.
	db 128	; Volume + possible Pitch up/down.
	db 137	; Note 33.
	db 8	; New instrument 4.
	db 21	; Note 45.
	db 204	; Note 36.
	db 4	; New instrument 2.
	db 129	; Volume + possible Pitch up/down.
	db 204	; Note 36.
	db 2	; New instrument 1.
	db 128	; Volume + possible Pitch up/down.
	db 191, 21	; Escaped note 21.
	db 8	; New instrument 4.
	db 204	; Note 36.
	db 4	; New instrument 2.
	db 129	; Volume + possible Pitch up/down.
	db 255, 9	; Escaped note 9.
	db 8	; New instrument 4.
	db 128	; Volume + possible Pitch up/down.
	db 145	; Note 41.
	db 6	; New instrument 3.
	db 142	; Note 38.
	db 8	; New instrument 4.
	db 209	; Note 41.
	db 6	; New instrument 3.
	db 128	; Volume + possible Pitch up/down.
	db 81	; Note 41.
	db 128	; Volume + possible Pitch up/down.

Untitled_Subsong0DisarkByteRegionEnd0
